version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    networks:
      - mynetwork
    ports:
      - "8080:8080"

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:

